apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
  labels:
    type: local
    app: example
spec:
  storageClassName: manual
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "<path-local>"

# kubectl apply -f example-pv.yaml
