apiVersion: v1
kind: ConfigMap
metadata:
  name: example-config
  labels:
    app: example
data:
  JAVA_OPTS: "-Xmx400M -Xms400M"
#Example Spring
#  SPRING_PROFILES_ACTIVE: <profile>
#  SPRING_DATASOURCE_URL: <url-database>
#  SPRING_DATASOURCE_USERNAME: <user-database>
#  SPRING_DATASOURCE_PASSWORD: <pass-database>
#  SPRING_CLOUD_CONSUL_HOST: <host-consul>
#  SPRING_CLOUD_CONSUL_PORT: <port-consul>


# kubectl apply -f example-configmap.yaml
