apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-claim
  labels:
    app: example
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100M

# kubectl apply -f example-pv-claim.yaml
