apiVersion: v1
kind: Service
metadata:
  name: example
  labels:
    app: example
spec:
  selector:
    app: example
  type: LoadBalancer
  ports:
    - port: <port-external>
      targetPort: <port-container>


# kubectl apply -f example-service.yaml
