apiVersion: v1
kind: Endpoints
metadata:
  name: example
  labels:
    app: example
subsets:
    - addresses:
        - ip: "<ip-external>"
      ports:
        - port: <port-external>
          name: example

# kubectl apply -f example-endpoint.yaml
